name: delete-old-workflow-runs
on:
  schedule:
    - cron: '15 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: ${{ github.repository }}
          older-than-seconds: 86400
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}